[module]
  [module.hugoVersion]
    extended = true
    min = "0.120.0"
  [[module.imports]]
    path = "github.com/gohugoio/hugo-mod-bootstrap-scss/v5"
    disable = false

[[runners]]
  environment = ["FF_DISABLE_UMASK_FOR_DOCKER_EXECUTOR=1", "GIT_CONFIG_COUNT=1", "GIT_CONFIG_KEY_0=safe.directory", "GIT_CONFIG_VALUE_0=*"]